CREATE TABLE PS_USER(
  USER_ID INTEGER NOT NULL AUTO_INCREMENT,
  USER_NOME VARCHAR(70) NOT NULL,
  USER_MATRICULA VARCHAR(20) UNIQUE NOT NULL,
  USER_EMAIL VARCHAR(70) UNIQUE NOT NULL,
  USER_TIPO ENUM('Servidor', 'Aluno','Professor') NOT NULL,
  USER_LOGIN VARCHAR(70) UNIQUE NOT NULL,
  USER_SENHA VARCHAR(70) UNIQUE NOT NULL,
  USER_SIAP INTEGER,
  USER_CPF INTEGER,
  CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);


CREATE TABLE PS_DISCIPLINA(
  DIS_ID INTEGER NOT NULL AUTO_INCREMENT,
  DIS_NOME VARCHAR(70) NOT NULL UNIQUE,
  DIS_USER_ID INTEGER NOT NULL,
  CONSTRAINT DIS_PK  PRIMARY KEY (DIS_ID),
  CONSTRAINT DIS_USER_FK FOREIGN KEY (DIS_USER_ID) REFERENCES PS_USER(USER_ID)
);


CREATE TABLE PS_FALTAS_ALUNOS(
  FAL_ID INTEGER NOT NULL AUTO_INCREMENT,
  FAL_DIS_ID INTEGER,
  FAL_USER_MATRICULA VARCHAR(20) NOT NULL,
  FAL_DATA_INICIAL DATE NOT NULL,
  FAL_DURACAO INTEGER NOT NULL,
  FAL_CURSO VARCHAR(40) NOT NULL,
  CONSTRAINT FAL_PK PRIMARY KEY (FAL_ID),
  CONSTRAINT FAL_DIS_FK FOREIGN KEY (FAL_DIS_ID) REFERENCES PS_DISCIPLINA(DIS_ID),
  CONSTRAINT FAL_USER_FK FOREIGN KEY (FAL_USER_MATRICULA) REFERENCES PS_USER(USER_MATRICULA)
);

CREATE TABLE PS_FALTAS_PROFESSOR(
  FAP_ID INTEGER NOT NULL AUTO_INCREMENT,
  FAP_USER_MATRICULA VARCHAR(20) NOT NULL,
  FAP_DIS_ID INTEGER ,
  FAP_DATA DATE NOT NULL,
  FAP_HORARIO VARCHAR(10) NOT NULL,
  FAP_DIS VARCHAR(40) NOT NULL,
  CONSTRAINT FAP_PK PRIMARY KEY (FAP_ID),
  CONSTRAINT FAP_USER_FK FOREIGN KEY (FAP_USER_MATRICULA) REFERENCES PS_USER(USER_MATRICULA),
  CONSTRAINT FAP_DIS_ID FOREIGN KEY (FAP_DIS_ID) REFERENCES PS_DISCIPLINA(DIS_ID)
);