CREATE TABLE PS_SERVIDOR(
  SER_ID INTEGER NOT NULL AUTO_INCREMENT,
  SER_NOME VARCHAR(70) NOT NULL,
  SER_SIAPE VARCHAR(20) UNIQUE NOT NULL,
  SER_EMAIL VARCHAR(70) UNIQUE NOT NULL,
  CONSTRAINT SER_PK PRIMARY KEY (SER_ID)
  );

CREATE TABLE PS_PROFESSOR(
  PRO_ID INTEGER NOT NULL AUTO_INCREMENT,
  PRO_NOME VARCHAR(70) NOT NULL,
  PRO_SIAPE VARCHAR(20) UNIQUE NOT NULL,
  PRO_EMAIL VARCHAR(70) UNIQUE NOT NULL,
  CONSTRAINT PRO_PK PRIMARY KEY (PRO_ID)
  );
CREATE TABLE PS_DISCIPLINA(
  DIS_ID INTEGER NOT NULL AUTO_INCREMENT,
  DIS_NOME VARCHAR(70) NOT NULL UNIQUE,
  DIS_PRO_ID INTEGER NOT NULL,
  CONSTRAINT DIS_PK  PRIMARY KEY (DIS_ID),
  CONSTRAINT DIS_PRO_FK FOREIGN KEY (DIS_PRO_ID) REFERENCES PS_PROFESSOR(PRO_ID)
);

CREATE TABLE PS_ALUNO(
  ALN_NOME VARCHAR(70) NOT NULL,
  ALN_MATRICULA VARCHAR(20) NOT NULL,
  ALN_EMAIL VARCHAR(70) UNIQUE NOT NULL,
  ALN_DIS_ID INTEGER,
  CONSTRAINT ALN_PK PRIMARY KEY (ALN_MATRICULA),
  CONSTRAINT ALN_DIS_FK FOREIGN KEY (ALN_DIS_ID) REFERENCES PS_DISCIPLINA(DIS_ID)
  );
CREATE TABLE PS_FALTAS_ALUNOS(
  FAL_ID INTEGER NOT NULL AUTO_INCREMENT,
  FAL_DIS_ID INTEGER,
  FAL_ALN_MATRICULA VARCHAR(20) NOT NULL,
  FAL_DATA_INICIAL DATE NOT NULL,
  FAL_DURACAO INTEGER NOT NULL,
  FAL_CURSO VARCHAR(40) NOT NULL,
  CONSTRAINT FAL_PK PRIMARY KEY (FAL_ID),
  CONSTRAINT FAL_DIS_FK FOREIGN KEY (FAL_DIS_ID) REFERENCES PS_DISCIPLINA(DIS_ID),
  CONSTRAINT FAL_ALN_FK FOREIGN KEY (FAL_ALN_MATRICULA) REFERENCES PS_ALUNO(ALN_MATRICULA)
);

CREATE TABLE PS_FALTAS_PROFESSOR(
  FAP_ID INTEGER NOT NULL AUTO_INCREMENT,
  FAP_ALN_MATRICULA VARCHAR(20) NOT NULL,
  FAP_DIS_ID INTEGER ,
  FAP_DATA DATE NOT NULL,
  FAP_HORARIO VARCHAR(10) NOT NULL,
  FAP_DIS VARCHAR(40) NOT NULL,
  CONSTRAINT FAP_PK PRIMARY KEY (FAP_ID),
  CONSTRAINT FAP_ALN_FK FOREIGN KEY (FAP_ALN_MATRICULA) REFERENCES PS_ALUNO(ALN_MATRICULA),
  CONSTRAINT FAP_DIS_ID FOREIGN KEY (FAP_DIS_ID) REFERENCES PS_DISCIPLINA(DIS_ID)
);




